function webgames(){var P='',wb='" for "gwt:onLoadErrorFn"',ub='" for "gwt:onPropertyErrorFn"',ib='"><\/script>',Z='#',Eb='&',xc='.cache.html',_='/',Wb='032BA73D01D287F7B618EC3F4AA92D02',Xb='0B87CF925D8678A542601A3C45994A18',Yb='1194F9938FCB250512B5A2F57657A1D3',$b='28D8877464D2FE6A5822DEBA5B0D1DB6',ac='2F6F43670223537011EF9E54ACCD70EE',bc='35BF5574278A65005BB5229E6A8A5AB8',cc='4FABE8C3A592EC33DBA49CC6B4FAB63A',dc='52BE1116A29E041C999352B905BA0D4A',ec='72A57CD992A99FBBBFEF077C8767E4EF',fc='877248B86E7375E50BE1EF99D953D2CC',hc='89BCCDBD54854CBCAA79BD94F6712E82',ic='8E81CDEE456A21DF20DBDED067C2BEE6',jc='8FB5913E64F7700DD8D52101DD3FBBBB',kc='9A111AEC41BD204C81D0A22B9D4F5796',lc='9AD628FFB22C411EFF4E5BDBBBA37378',wc=':',ob='::',Fc='<script defer="defer">webgames.onInjectionDone(\'webgames\')<\/script>',hb='<script id="',rb='=',$='?',mc='A2583C1DE60D51D118D228319A04DF4D',nc='AE0657D07852580F1175D698154B0535',oc='BD998B9E2C287653D2053D5887440064',tb='Bad handler "',pc='CD1828F241C5F298C39935703512F17D',qc='D57B2E7B54C7C0A3D50D73A372DC74FF',rc='DCFF1AD732F66D71C778F384B4425FBB',sc='DED8814F89628D9590B65E5481C49575',Ec='DOMContentLoaded',tc='E3C99D2F605A3DBA234DBB606F760C66',uc='E50ACA915B9BFB02FCE550A40077032C',vc='E551462DC1FDF4AAE7AAA00004049F16',jb='SCRIPT',Hb='Unexpected exception in locale detection, using default: ',Gb='_',Fb='__gwt_Locale',gb='__gwt_marker_webgames',kb='base',cb='baseUrl',T='begin',S='bootstrap',bb='clear.cache.gif',qb='content',Cb='en',Y='end',_b='fa',Vb='fr',Pb='gecko',Qb='gecko1_8',U='gwt.codesvr=',V='gwt.hosted=',W='gwt.hybrid',yc='gwt/standard/standard.css',vb='gwt:onLoadErrorFn',sb='gwt:onPropertyErrorFn',pb='gwt:property',Dc='head',Tb='hosted.html?webgames',Cc='href',Ob='ie6',Nb='ie8',xb='iframe',ab='img',yb="javascript:''",gc='ko',zc='link',Sb='loadExternalRefs',Bb='locale',Db='locale=',lb='meta',Ab='moduleRequested',X='moduleStartup',Mb='msie',mb='name',Jb='opera',zb='position:absolute;width:0;height:0;border:none',Ac='rel',Lb='safari',db='script',Ub='selectingPermutation',R='startup',Bc='stylesheet',Zb='tr',fb='undefined',Rb='unknown',Ib='user.agent',Q='webgames',eb='webgames.nocache.js',nb='webgames::',Kb='webkit';var l=window,m=document,n=l.__gwtStatsEvent?function(a){return l.__gwtStatsEvent(a)}:null,o=l.__gwtStatsSessionId?l.__gwtStatsSessionId:null,p,q,r,s=P,t={},u=[],v=[],w=[],x=0,y,z;n&&n({moduleName:Q,sessionId:o,subSystem:R,evtGroup:S,millis:(new Date).getTime(),type:T});if(!l.__gwt_stylesLoaded){l.__gwt_stylesLoaded={}}if(!l.__gwt_scriptsLoaded){l.__gwt_scriptsLoaded={}}function A(){var b=false;try{var c=l.location.search;return (c.indexOf(U)!=-1||(c.indexOf(V)!=-1||l.external&&l.external.gwtOnLoad))&&c.indexOf(W)==-1}catch(a){}A=function(){return b};return b}
function B(){if(p&&q){var b=m.getElementById(Q);var c=b.contentWindow;if(A()){c.__gwt_getProperty=function(a){return H(a)}}webgames=null;c.gwtOnLoad(y,Q,s,x);n&&n({moduleName:Q,sessionId:o,subSystem:R,evtGroup:X,millis:(new Date).getTime(),type:Y})}}
function C(){function e(a){var b=a.lastIndexOf(Z);if(b==-1){b=a.length}var c=a.indexOf($);if(c==-1){c=a.length}var d=a.lastIndexOf(_,Math.min(c,b));return d>=0?a.substring(0,d+1):P}
function f(a){if(a.match(/^\w+:\/\//)){}else{var b=m.createElement(ab);b.src=a+bb;a=e(b.src)}return a}
function g(){var a=F(cb);if(a!=null){return a}return P}
function h(){var a=m.getElementsByTagName(db);for(var b=0;b<a.length;++b){if(a[b].src.indexOf(eb)!=-1){return e(a[b].src)}}return P}
function i(){var a;if(typeof isBodyLoaded==fb||!isBodyLoaded()){var b=gb;var c;m.write(hb+b+ib);c=m.getElementById(b);a=c&&c.previousSibling;while(a&&a.tagName!=jb){a=a.previousSibling}if(c){c.parentNode.removeChild(c)}if(a&&a.src){return e(a.src)}}return P}
function j(){var a=m.getElementsByTagName(kb);if(a.length>0){return a[a.length-1].href}return P}
var k=g();if(k==P){k=h()}if(k==P){k=i()}if(k==P){k=j()}if(k==P){k=e(m.location.href)}k=f(k);s=k;return k}
function D(){var b=document.getElementsByTagName(lb);for(var c=0,d=b.length;c<d;++c){var e=b[c],f=e.getAttribute(mb),g;if(f){f=f.replace(nb,P);if(f.indexOf(ob)>=0){continue}if(f==pb){g=e.getAttribute(qb);if(g){var h,i=g.indexOf(rb);if(i>=0){f=g.substring(0,i);h=g.substring(i+1)}else{f=g;h=P}t[f]=h}}else if(f==sb){g=e.getAttribute(qb);if(g){try{z=eval(g)}catch(a){alert(tb+g+ub)}}}else if(f==vb){g=e.getAttribute(qb);if(g){try{y=eval(g)}catch(a){alert(tb+g+wb)}}}}}}
function E(a,b){return b in u[a]}
function F(a){var b=t[a];return b==null?null:b}
function G(a,b){var c=w;for(var d=0,e=a.length-1;d<e;++d){c=c[a[d]]||(c[a[d]]=[])}c[a[e]]=b}
function H(a){var b=v[a](),c=u[a];if(b in c){return b}var d=[];for(var e in c){d[c[e]]=e}if(z){z(a,d,b)}throw null}
var I;function J(){if(!I){I=true;var a=m.createElement(xb);a.src=yb;a.id=Q;a.style.cssText=zb;a.tabIndex=-1;m.body.appendChild(a);n&&n({moduleName:Q,sessionId:o,subSystem:R,evtGroup:X,millis:(new Date).getTime(),type:Ab});a.contentWindow.location.replace(s+L)}}
v[Bb]=function(){var b=null;var c=Cb;try{if(!b){var d=location.search;var e=d.indexOf(Db);if(e>=0){var f=d.substring(e+7);var g=d.indexOf(Eb,e);if(g<0){g=d.length}b=d.substring(e+7,g)}}if(!b){b=F(Bb)}if(!b){b=l[Fb]}if(b){c=b}while(b&&!E(Bb,b)){var h=b.lastIndexOf(Gb);if(h<0){b=null;break}b=b.substring(0,h)}}catch(a){alert(Hb+a)}l[Fb]=c;return b||Cb};u[Bb]={'default':0,en:1,fa:2,fr:3,ko:4,tr:5};v[Ib]=function(){var b=navigator.userAgent.toLowerCase();var c=function(a){return parseInt(a[1])*1000+parseInt(a[2])};if(b.indexOf(Jb)!=-1){return Jb}else if(b.indexOf(Kb)!=-1){return Lb}else if(b.indexOf(Mb)!=-1){if(document.documentMode>=8){return Nb}else{var d=/msie ([0-9]+)\.([0-9]+)/.exec(b);if(d&&d.length==3){var e=c(d);if(e>=6000){return Ob}}}}else if(b.indexOf(Pb)!=-1){return Qb}return Rb};u[Ib]={gecko1_8:0,ie6:1,ie8:2,opera:3,safari:4};webgames.onScriptLoad=function(){if(I){q=true;B()}};webgames.onInjectionDone=function(){p=true;n&&n({moduleName:Q,sessionId:o,subSystem:R,evtGroup:Sb,millis:(new Date).getTime(),type:Y});B()};D();C();var K;var L;if(A()){if(l.external&&(l.external.initModule&&l.external.initModule(Q))){l.location.reload();return}L=Tb;K=P}n&&n({moduleName:Q,sessionId:o,subSystem:R,evtGroup:S,millis:(new Date).getTime(),type:Ub});if(!A()){try{G([Vb,Jb],Wb);G([Vb,Ob],Xb);G([Cb,Jb],Yb);G([Zb,Ob],$b);G([_b,Lb],ac);G([_b,Qb],bc);G([Zb,Qb],cc);G([_b,Jb],dc);G([Vb,Lb],ec);G([Cb,Ob],fc);G([gc,Ob],hc);G([Cb,Qb],ic);G([Cb,Nb],jc);G([gc,Qb],kc);G([gc,Nb],lc);G([Zb,Jb],mc);G([Zb,Lb],nc);G([Cb,Lb],oc);G([gc,Jb],pc);G([Vb,Nb],qc);G([_b,Ob],rc);G([gc,Lb],sc);G([Zb,Nb],tc);G([_b,Nb],uc);G([Vb,Qb],vc);K=w[H(Bb)][H(Ib)];var M=K.indexOf(wc);if(M!=-1){x=Number(K.substring(M+1));K=K.substring(0,M)}L=K+xc}catch(a){return}}var N;function O(){if(!r){r=true;if(!__gwt_stylesLoaded[yc]){var a=m.createElement(zc);__gwt_stylesLoaded[yc]=a;a.setAttribute(Ac,Bc);a.setAttribute(Cc,s+yc);m.getElementsByTagName(Dc)[0].appendChild(a)}B();if(m.removeEventListener){m.removeEventListener(Ec,O,false)}if(N){clearInterval(N)}}}
if(m.addEventListener){m.addEventListener(Ec,function(){J();O()},false)}var N=setInterval(function(){if(/loaded|complete/.test(m.readyState)){J();O()}},50);n&&n({moduleName:Q,sessionId:o,subSystem:R,evtGroup:S,millis:(new Date).getTime(),type:Y});n&&n({moduleName:Q,sessionId:o,subSystem:R,evtGroup:Sb,millis:(new Date).getTime(),type:T});m.write(Fc)}
webgames();