function webgames(){var P='',wb='" for "gwt:onLoadErrorFn"',ub='" for "gwt:onPropertyErrorFn"',ib='"><\/script>',Z='#',Eb='&',xc='.cache.html',_='/',Wb='0626275FB75DD181C442F2B0613CA24A',Yb='0CFF7975A015020094F203A6DBC68DF8',$b='18FA6CBB1CF5F908B473B364C784F79E',ac='2152A14FE598D9D369145139EA28D807',bc='258A3B3CF38BCE52991FADDD8B945B13',cc='393A49128672DD8A426930DC1243DC80',dc='4BE09D8E4F4987D80948E94741276154',ec='53BCB5B0052255D01C31F7F1726B70EC',fc='58BA67751480BF385E7AE6A9DC752F41',gc='592715D80478F9186DE785B4D0A8A41E',hc='65C340FF198F5832A62D521EC377C667',ic='67EBC9B1D11DFE8435B05B770B8BA29F',jc='6AD54D90DD665C731E410579D514554A',kc='71ABB81D6EE528F6DA05517E0CD97967',lc='72F5C908DC5920EA71F566D6D2F51536',mc='98BF07F12D1F1978DD21D46BB660D75C',nc='9DB4BE59BF1D183EC9CA8E2B2C54567C',wc=':',ob='::',Fc='<script defer="defer">webgames.onInjectionDone(\'webgames\')<\/script>',hb='<script id="',rb='=',$='?',tb='Bad handler "',oc='C26228E8D51E004C0D605007CF1E0768',pc='C3491C7746A1D49AFD9F3C03E0BA6B7A',qc='CAC07763F002B4329B94E2721EF0799C',rc='DBEA9CF4374D4C7F8ABBE2610D2495B7',Ec='DOMContentLoaded',sc='F9E41086E973236545EF626C45F42B8C',tc='FA1ACFE6A34F5AAC450312657B2C9AE8',uc='FB5054D8C5BED61ED9A8ADC3C3507A7C',vc='FF23DED15717B7447295FA190E72D13A',jb='SCRIPT',Hb='Unexpected exception in locale detection, using default: ',Gb='_',Fb='__gwt_Locale',gb='__gwt_marker_webgames',kb='base',cb='baseUrl',T='begin',S='bootstrap',bb='clear.cache.gif',qb='content',Cb='en',Y='end',Zb='fa',_b='fr',Pb='gecko',Qb='gecko1_8',U='gwt.codesvr=',V='gwt.hosted=',W='gwt.hybrid',yc='gwt/standard/standard.css',vb='gwt:onLoadErrorFn',sb='gwt:onPropertyErrorFn',pb='gwt:property',Dc='head',Tb='hosted.html?webgames',Cc='href',Ob='ie6',Nb='ie8',xb='iframe',ab='img',yb="javascript:''",Xb='ko',zc='link',Sb='loadExternalRefs',Bb='locale',Db='locale=',lb='meta',Ab='moduleRequested',X='moduleStartup',Mb='msie',mb='name',Jb='opera',zb='position:absolute;width:0;height:0;border:none',Ac='rel',Lb='safari',db='script',Ub='selectingPermutation',R='startup',Bc='stylesheet',Vb='tr',fb='undefined',Rb='unknown',Ib='user.agent',Q='webgames',eb='webgames.nocache.js',nb='webgames::',Kb='webkit';var l=window,m=document,n=l.__gwtStatsEvent?function(a){return l.__gwtStatsEvent(a)}:null,o=l.__gwtStatsSessionId?l.__gwtStatsSessionId:null,p,q,r,s=P,t={},u=[],v=[],w=[],x=0,y,z;n&&n({moduleName:Q,sessionId:o,subSystem:R,evtGroup:S,millis:(new Date).getTime(),type:T});if(!l.__gwt_stylesLoaded){l.__gwt_stylesLoaded={}}if(!l.__gwt_scriptsLoaded){l.__gwt_scriptsLoaded={}}function A(){var b=false;try{var c=l.location.search;return (c.indexOf(U)!=-1||(c.indexOf(V)!=-1||l.external&&l.external.gwtOnLoad))&&c.indexOf(W)==-1}catch(a){}A=function(){return b};return b}
function B(){if(p&&q){var b=m.getElementById(Q);var c=b.contentWindow;if(A()){c.__gwt_getProperty=function(a){return H(a)}}webgames=null;c.gwtOnLoad(y,Q,s,x);n&&n({moduleName:Q,sessionId:o,subSystem:R,evtGroup:X,millis:(new Date).getTime(),type:Y})}}
function C(){function e(a){var b=a.lastIndexOf(Z);if(b==-1){b=a.length}var c=a.indexOf($);if(c==-1){c=a.length}var d=a.lastIndexOf(_,Math.min(c,b));return d>=0?a.substring(0,d+1):P}
function f(a){if(a.match(/^\w+:\/\//)){}else{var b=m.createElement(ab);b.src=a+bb;a=e(b.src)}return a}
function g(){var a=F(cb);if(a!=null){return a}return P}
function h(){var a=m.getElementsByTagName(db);for(var b=0;b<a.length;++b){if(a[b].src.indexOf(eb)!=-1){return e(a[b].src)}}return P}
function i(){var a;if(typeof isBodyLoaded==fb||!isBodyLoaded()){var b=gb;var c;m.write(hb+b+ib);c=m.getElementById(b);a=c&&c.previousSibling;while(a&&a.tagName!=jb){a=a.previousSibling}if(c){c.parentNode.removeChild(c)}if(a&&a.src){return e(a.src)}}return P}
function j(){var a=m.getElementsByTagName(kb);if(a.length>0){return a[a.length-1].href}return P}
var k=g();if(k==P){k=h()}if(k==P){k=i()}if(k==P){k=j()}if(k==P){k=e(m.location.href)}k=f(k);s=k;return k}
function D(){var b=document.getElementsByTagName(lb);for(var c=0,d=b.length;c<d;++c){var e=b[c],f=e.getAttribute(mb),g;if(f){f=f.replace(nb,P);if(f.indexOf(ob)>=0){continue}if(f==pb){g=e.getAttribute(qb);if(g){var h,i=g.indexOf(rb);if(i>=0){f=g.substring(0,i);h=g.substring(i+1)}else{f=g;h=P}t[f]=h}}else if(f==sb){g=e.getAttribute(qb);if(g){try{z=eval(g)}catch(a){alert(tb+g+ub)}}}else if(f==vb){g=e.getAttribute(qb);if(g){try{y=eval(g)}catch(a){alert(tb+g+wb)}}}}}}
function E(a,b){return b in u[a]}
function F(a){var b=t[a];return b==null?null:b}
function G(a,b){var c=w;for(var d=0,e=a.length-1;d<e;++d){c=c[a[d]]||(c[a[d]]=[])}c[a[e]]=b}
function H(a){var b=v[a](),c=u[a];if(b in c){return b}var d=[];for(var e in c){d[c[e]]=e}if(z){z(a,d,b)}throw null}
var I;function J(){if(!I){I=true;var a=m.createElement(xb);a.src=yb;a.id=Q;a.style.cssText=zb;a.tabIndex=-1;m.body.appendChild(a);n&&n({moduleName:Q,sessionId:o,subSystem:R,evtGroup:X,millis:(new Date).getTime(),type:Ab});a.contentWindow.location.replace(s+L)}}
v[Bb]=function(){var b=null;var c=Cb;try{if(!b){var d=location.search;var e=d.indexOf(Db);if(e>=0){var f=d.substring(e+7);var g=d.indexOf(Eb,e);if(g<0){g=d.length}b=d.substring(e+7,g)}}if(!b){b=F(Bb)}if(!b){b=l[Fb]}if(b){c=b}while(b&&!E(Bb,b)){var h=b.lastIndexOf(Gb);if(h<0){b=null;break}b=b.substring(0,h)}}catch(a){alert(Hb+a)}l[Fb]=c;return b||Cb};u[Bb]={'default':0,en:1,fa:2,fr:3,ko:4,tr:5};v[Ib]=function(){var b=navigator.userAgent.toLowerCase();var c=function(a){return parseInt(a[1])*1000+parseInt(a[2])};if(b.indexOf(Jb)!=-1){return Jb}else if(b.indexOf(Kb)!=-1){return Lb}else if(b.indexOf(Mb)!=-1){if(document.documentMode>=8){return Nb}else{var d=/msie ([0-9]+)\.([0-9]+)/.exec(b);if(d&&d.length==3){var e=c(d);if(e>=6000){return Ob}}}}else if(b.indexOf(Pb)!=-1){return Qb}return Rb};u[Ib]={gecko1_8:0,ie6:1,ie8:2,opera:3,safari:4};webgames.onScriptLoad=function(){if(I){q=true;B()}};webgames.onInjectionDone=function(){p=true;n&&n({moduleName:Q,sessionId:o,subSystem:R,evtGroup:Sb,millis:(new Date).getTime(),type:Y});B()};D();C();var K;var L;if(A()){if(l.external&&(l.external.initModule&&l.external.initModule(Q))){l.location.reload();return}L=Tb;K=P}n&&n({moduleName:Q,sessionId:o,subSystem:R,evtGroup:S,millis:(new Date).getTime(),type:Ub});if(!A()){try{G([Vb,Jb],Wb);G([Xb,Ob],Yb);G([Zb,Ob],$b);G([_b,Lb],ac);G([Zb,Qb],bc);G([Cb,Nb],cc);G([_b,Nb],dc);G([Xb,Lb],ec);G([Xb,Jb],fc);G([Vb,Qb],gc);G([Cb,Ob],hc);G([Vb,Nb],ic);G([Vb,Lb],jc);G([Cb,Lb],kc);G([Cb,Qb],lc);G([Xb,Qb],mc);G([Zb,Nb],nc);G([_b,Qb],oc);G([Vb,Ob],pc);G([_b,Ob],qc);G([Zb,Jb],rc);G([_b,Jb],sc);G([Zb,Lb],tc);G([Xb,Nb],uc);G([Cb,Jb],vc);K=w[H(Bb)][H(Ib)];var M=K.indexOf(wc);if(M!=-1){x=Number(K.substring(M+1));K=K.substring(0,M)}L=K+xc}catch(a){return}}var N;function O(){if(!r){r=true;if(!__gwt_stylesLoaded[yc]){var a=m.createElement(zc);__gwt_stylesLoaded[yc]=a;a.setAttribute(Ac,Bc);a.setAttribute(Cc,s+yc);m.getElementsByTagName(Dc)[0].appendChild(a)}B();if(m.removeEventListener){m.removeEventListener(Ec,O,false)}if(N){clearInterval(N)}}}
if(m.addEventListener){m.addEventListener(Ec,function(){J();O()},false)}var N=setInterval(function(){if(/loaded|complete/.test(m.readyState)){J();O()}},50);n&&n({moduleName:Q,sessionId:o,subSystem:R,evtGroup:S,millis:(new Date).getTime(),type:Y});n&&n({moduleName:Q,sessionId:o,subSystem:R,evtGroup:Sb,millis:(new Date).getTime(),type:T});m.write(Fc)}
webgames();