function webgames(){var P='',wb='" for "gwt:onLoadErrorFn"',ub='" for "gwt:onPropertyErrorFn"',ib='"><\/script>',Z='#',Eb='&',xc='.cache.html',_='/',Vb='01288C41DD625341F902439C0CC5E37E',Xb='0AFBBC819511762F4F64D1AB3A6059DE',Yb='0DBE7A238A1DD1A6E615EDE4184BE54A',Zb='1738530920BB19F1B5B68137672AF988',_b='216C41BAC5C3AC870FB8670FB6D0C87E',ac='335C9CCCF0B39734CC50D23A94455155',bc='3B8EEB31B53133128D14065DFE7080A5',cc='44CA56A5CE26629F61C613C8156D03B7',ec='4769B52100864D933F3F921E0F081AF1',fc='4F84327CB6F59AD75B9A8C0F8F437093',hc='71B9BD224887DA4D60CDFAF1C58D64D9',ic='7888427BD51FCF3D588A9718AF775667',jc='885CB16801C233E1D82499A7020C35A2',kc='92576644127ECFCD40F057A067B80E2B',wc=':',ob='::',Fc='<script defer="defer">webgames.onInjectionDone(\'webgames\')<\/script>',hb='<script id="',rb='=',$='?',lc='B3E7C1710991C28B7175E74F5ED4DA4A',mc='B56BFAC4391CC177DB0D6E4EDF30CC7C',nc='B5710EFA933CBC072DEBD094BDCC80E5',tb='Bad handler "',oc='D52584353FA7E0FB71636869487306B7',pc='D5D161EE443788F5C45483A1DB01621D',qc='D9B3DA1BA53C885D8617230B0AB3628F',rc='DA4E6175F0EAF50B91E2021A47602D74',sc='DC57309F614E2FF665254A21BFB39047',tc='DC8E4DAEB6395617240775F8534D1561',Ec='DOMContentLoaded',uc='E9626D0D2AA372BD198426420F358772',vc='FF95762C8626B88D2F2A5B1C01697369',jb='SCRIPT',Hb='Unexpected exception in locale detection, using default: ',Gb='_',Fb='__gwt_Locale',gb='__gwt_marker_webgames',kb='base',cb='baseUrl',T='begin',S='bootstrap',bb='clear.cache.gif',qb='content',Cb='en',Y='end',dc='fa',$b='fr',Pb='gecko',Qb='gecko1_8',U='gwt.codesvr=',V='gwt.hosted=',W='gwt.hybrid',yc='gwt/standard/standard.css',vb='gwt:onLoadErrorFn',sb='gwt:onPropertyErrorFn',pb='gwt:property',Dc='head',Tb='hosted.html?webgames',Cc='href',Ob='ie6',Nb='ie8',xb='iframe',ab='img',yb="javascript:''",Wb='ko',zc='link',Sb='loadExternalRefs',Bb='locale',Db='locale=',lb='meta',Ab='moduleRequested',X='moduleStartup',Mb='msie',mb='name',Jb='opera',zb='position:absolute;width:0;height:0;border:none',Ac='rel',Lb='safari',db='script',Ub='selectingPermutation',R='startup',Bc='stylesheet',gc='tr',fb='undefined',Rb='unknown',Ib='user.agent',Q='webgames',eb='webgames.nocache.js',nb='webgames::',Kb='webkit';var l=window,m=document,n=l.__gwtStatsEvent?function(a){return l.__gwtStatsEvent(a)}:null,o=l.__gwtStatsSessionId?l.__gwtStatsSessionId:null,p,q,r,s=P,t={},u=[],v=[],w=[],x=0,y,z;n&&n({moduleName:Q,sessionId:o,subSystem:R,evtGroup:S,millis:(new Date).getTime(),type:T});if(!l.__gwt_stylesLoaded){l.__gwt_stylesLoaded={}}if(!l.__gwt_scriptsLoaded){l.__gwt_scriptsLoaded={}}function A(){var b=false;try{var c=l.location.search;return (c.indexOf(U)!=-1||(c.indexOf(V)!=-1||l.external&&l.external.gwtOnLoad))&&c.indexOf(W)==-1}catch(a){}A=function(){return b};return b}
function B(){if(p&&q){var b=m.getElementById(Q);var c=b.contentWindow;if(A()){c.__gwt_getProperty=function(a){return H(a)}}webgames=null;c.gwtOnLoad(y,Q,s,x);n&&n({moduleName:Q,sessionId:o,subSystem:R,evtGroup:X,millis:(new Date).getTime(),type:Y})}}
function C(){function e(a){var b=a.lastIndexOf(Z);if(b==-1){b=a.length}var c=a.indexOf($);if(c==-1){c=a.length}var d=a.lastIndexOf(_,Math.min(c,b));return d>=0?a.substring(0,d+1):P}
function f(a){if(a.match(/^\w+:\/\//)){}else{var b=m.createElement(ab);b.src=a+bb;a=e(b.src)}return a}
function g(){var a=F(cb);if(a!=null){return a}return P}
function h(){var a=m.getElementsByTagName(db);for(var b=0;b<a.length;++b){if(a[b].src.indexOf(eb)!=-1){return e(a[b].src)}}return P}
function i(){var a;if(typeof isBodyLoaded==fb||!isBodyLoaded()){var b=gb;var c;m.write(hb+b+ib);c=m.getElementById(b);a=c&&c.previousSibling;while(a&&a.tagName!=jb){a=a.previousSibling}if(c){c.parentNode.removeChild(c)}if(a&&a.src){return e(a.src)}}return P}
function j(){var a=m.getElementsByTagName(kb);if(a.length>0){return a[a.length-1].href}return P}
var k=g();if(k==P){k=h()}if(k==P){k=i()}if(k==P){k=j()}if(k==P){k=e(m.location.href)}k=f(k);s=k;return k}
function D(){var b=document.getElementsByTagName(lb);for(var c=0,d=b.length;c<d;++c){var e=b[c],f=e.getAttribute(mb),g;if(f){f=f.replace(nb,P);if(f.indexOf(ob)>=0){continue}if(f==pb){g=e.getAttribute(qb);if(g){var h,i=g.indexOf(rb);if(i>=0){f=g.substring(0,i);h=g.substring(i+1)}else{f=g;h=P}t[f]=h}}else if(f==sb){g=e.getAttribute(qb);if(g){try{z=eval(g)}catch(a){alert(tb+g+ub)}}}else if(f==vb){g=e.getAttribute(qb);if(g){try{y=eval(g)}catch(a){alert(tb+g+wb)}}}}}}
function E(a,b){return b in u[a]}
function F(a){var b=t[a];return b==null?null:b}
function G(a,b){var c=w;for(var d=0,e=a.length-1;d<e;++d){c=c[a[d]]||(c[a[d]]=[])}c[a[e]]=b}
function H(a){var b=v[a](),c=u[a];if(b in c){return b}var d=[];for(var e in c){d[c[e]]=e}if(z){z(a,d,b)}throw null}
var I;function J(){if(!I){I=true;var a=m.createElement(xb);a.src=yb;a.id=Q;a.style.cssText=zb;a.tabIndex=-1;m.body.appendChild(a);n&&n({moduleName:Q,sessionId:o,subSystem:R,evtGroup:X,millis:(new Date).getTime(),type:Ab});a.contentWindow.location.replace(s+L)}}
v[Bb]=function(){var b=null;var c=Cb;try{if(!b){var d=location.search;var e=d.indexOf(Db);if(e>=0){var f=d.substring(e+7);var g=d.indexOf(Eb,e);if(g<0){g=d.length}b=d.substring(e+7,g)}}if(!b){b=F(Bb)}if(!b){b=l[Fb]}if(b){c=b}while(b&&!E(Bb,b)){var h=b.lastIndexOf(Gb);if(h<0){b=null;break}b=b.substring(0,h)}}catch(a){alert(Hb+a)}l[Fb]=c;return b||Cb};u[Bb]={'default':0,en:1,fa:2,fr:3,ko:4,tr:5};v[Ib]=function(){var b=navigator.userAgent.toLowerCase();var c=function(a){return parseInt(a[1])*1000+parseInt(a[2])};if(b.indexOf(Jb)!=-1){return Jb}else if(b.indexOf(Kb)!=-1){return Lb}else if(b.indexOf(Mb)!=-1){if(document.documentMode>=8){return Nb}else{var d=/msie ([0-9]+)\.([0-9]+)/.exec(b);if(d&&d.length==3){var e=c(d);if(e>=6000){return Ob}}}}else if(b.indexOf(Pb)!=-1){return Qb}return Rb};u[Ib]={gecko1_8:0,ie6:1,ie8:2,opera:3,safari:4};webgames.onScriptLoad=function(){if(I){q=true;B()}};webgames.onInjectionDone=function(){p=true;n&&n({moduleName:Q,sessionId:o,subSystem:R,evtGroup:Sb,millis:(new Date).getTime(),type:Y});B()};D();C();var K;var L;if(A()){if(l.external&&(l.external.initModule&&l.external.initModule(Q))){l.location.reload();return}L=Tb;K=P}n&&n({moduleName:Q,sessionId:o,subSystem:R,evtGroup:S,millis:(new Date).getTime(),type:Ub});if(!A()){try{G([Cb,Lb],Vb);G([Wb,Jb],Xb);G([Wb,Nb],Yb);G([Wb,Qb],Zb);G([$b,Qb],_b);G([$b,Jb],ac);G([Cb,Nb],bc);G([Cb,Qb],cc);G([dc,Nb],ec);G([dc,Jb],fc);G([gc,Qb],hc);G([dc,Lb],ic);G([$b,Nb],jc);G([gc,Jb],kc);G([Wb,Lb],lc);G([Wb,Ob],mc);G([gc,Ob],nc);G([dc,Ob],oc);G([dc,Qb],pc);G([Cb,Jb],qc);G([$b,Ob],rc);G([gc,Lb],sc);G([Cb,Ob],tc);G([gc,Nb],uc);G([$b,Lb],vc);K=w[H(Bb)][H(Ib)];var M=K.indexOf(wc);if(M!=-1){x=Number(K.substring(M+1));K=K.substring(0,M)}L=K+xc}catch(a){return}}var N;function O(){if(!r){r=true;if(!__gwt_stylesLoaded[yc]){var a=m.createElement(zc);__gwt_stylesLoaded[yc]=a;a.setAttribute(Ac,Bc);a.setAttribute(Cc,s+yc);m.getElementsByTagName(Dc)[0].appendChild(a)}B();if(m.removeEventListener){m.removeEventListener(Ec,O,false)}if(N){clearInterval(N)}}}
if(m.addEventListener){m.addEventListener(Ec,function(){J();O()},false)}var N=setInterval(function(){if(/loaded|complete/.test(m.readyState)){J();O()}},50);n&&n({moduleName:Q,sessionId:o,subSystem:R,evtGroup:S,millis:(new Date).getTime(),type:Y});n&&n({moduleName:Q,sessionId:o,subSystem:R,evtGroup:Sb,millis:(new Date).getTime(),type:T});m.write(Fc)}
webgames();